Epoch 1/20 [Train]:   0%|                                                                                                  | 0/8 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/backend/scripts/train_all_models.py", line 170, in <module>
    main()
    ~~~~^^
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/backend/scripts/train_all_models.py", line 131, in main
    trained_model = trainer.train(train_dataset, val_dataset, epochs=config['max_epochs'])
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/backend/core/train_models.py", line 115, in train
    for batch in train_pbar:
                 ^^^^^^^^^^
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py", line 733, in __next__
    data = self._next_data()
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py", line 1515, in _next_data
    return self._process_data(data, worker_id)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py", line 1550, in _process_data
    data.reraise()
    ~~~~~~~~~~~~^^
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/torch/_utils.py", line 750, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/.venv/lib/python3.13/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/Users/prashishshrestha/Desktop/Assignment_3_Major_Project/guardian_llm/backend/core/train_models.py", line 43, in __getitem__
    paper['annotations']['bias_fairness'],
    ~~~~~^^^^^^^^^^^^^^^
KeyError: 'annotations'
